# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1459396047);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1459396167);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1459396000175");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1459397730175");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1459395955759");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1459399555759");
user_pref("browser.search.countryCode", "AU");
user_pref("browser.search.region", "AU");
user_pref("browser.slowStartup.averageTime", 1577);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20160315153207");
user_pref("browser.startup.homepage_override.mstone", "45.0.1");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"pocket-button\",\"downloads-button\",\"home-button\",\"loop-button\"]},\"seen\":[\"loop-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\"],\"currentVersion\":5,\"newElementCount\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1459482326637");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1459395987838");
user_pref("datareporting.policy.firstRunTime", "1459395926637");
user_pref("datareporting.sessions.current.activeTicks", 10);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1403);
user_pref("datareporting.sessions.current.main", 49);
user_pref("datareporting.sessions.current.sessionRestored", 1595);
user_pref("datareporting.sessions.current.startTime", "1459395926242");
user_pref("datareporting.sessions.current.totalTime", 334);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"0.1\",\"type\":\"extension\",\"descriptor\":\"/Users/jasminelei/Desktop/Firefox.app/Contents/Resources/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.0.1");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.0.1");
user_pref("extensions.lastPlatformVersion", "45.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/Users/jasminelei/Desktop/Firefox.app/Contents/Resources/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"0.1\",\"st\":1458546215000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/Users/jasminelei/Desktop/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.0.1\",\"st\":1458546215000}}}");
user_pref("gecko.buildID", "20160315153207");
user_pref("gecko.mstone", "45.0.1");
user_pref("gfx.crash-guard.glcontext.appVersion", "45.0.1");
user_pref("gfx.crash-guard.glcontext.deviceID", "0x162b");
user_pref("gfx.crash-guard.status.glcontext", 2);
user_pref("media.gmp-manager.buildID", "20160315153207");
user_pref("media.gmp-manager.lastCheck", 1459395989);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1459395926);
user_pref("toolkit.telemetry.cachedClientID", "8efb9e3b-3691-f048-9f27-894a6196780f");
user_pref("toolkit.telemetry.previousBuildID", "20160315153207");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
